# Generated by Django 4.1.6 on 2023-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_options_remove_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='events',
            field=models.ManyToManyField(null=True, related_name='events', to='main.event'),
        ),
    ]
