# Generated by Django 4.1.6 on 2023-02-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='events',
            field=models.ManyToManyField(null=True, related_name='events_presenting', to='main.event'),
        ),
    ]
