# Generated by Django 4.1.6 on 2023-02-12 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_event_participants_alter_participant_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='events',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='events',
        ),
    ]
