# Generated by Django 4.1.6 on 2023-02-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_category_events_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='participants', to='main.participant'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, related_name='events_presenting', to='main.event'),
        ),
    ]
