# Generated by Django 4.1.6 on 2023-02-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_event_participants_remove_speaker_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='registered_event', to='main.participant'),
        ),
    ]
