# Generated by Django 4.1.6 on 2023-02-14 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_alter_event_category_alter_event_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(null=True, upload_to='speakers'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='attendant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='presenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
